name: Run tests

on:
  push:

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          php_extensions: xdebug
          args: tests --coverage-clover coverage.xml

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
